# Generated by Django 5.1.7 on 2025-03-08 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create", models.DateField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("service", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("lni-cog", "engrenagem"),
                            ("lni-stats-up", "grafico"),
                            ("ni-users", "users"),
                            ("lni-layers", "design"),
                            ("lni-mobile", "mobile"),
                            ("lni-rocket", "rocket"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create", models.DateField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "pic_profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="fusion/media/%y/%m/%d"
                    ),
                ),
                ("facebook", models.CharField(default="#", max_length=100)),
                ("twitter", models.CharField(default="#", max_length=100)),
                ("instagram", models.CharField(default="#", max_length=100)),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.servicemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
