# Generated by Django 5.1.7 on 2025-03-08 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create", models.DateField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("front_end_developer", "Front-end Developer"),
                            ("back_end_developer", "Back-end Developer"),
                            ("front_end_developer", "Front-end Developer"),
                            ("product_desiner", "Designer de Produto"),
                            ("lead_designer", "Designer Lider"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="teammodel",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.cargomodel",
            ),
        ),
    ]
