# Generated by Django 5.1.7 on 2025-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_cargomodel_alter_teammodel_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammodel",
            name="bio",
            field=models.CharField(default="Sem Biografia", max_length=150),
        ),
    ]
