# Generated by Django 5.1.7 on 2025-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_teammodel_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemodel",
            name="icon",
            field=models.CharField(
                choices=[
                    ("lni-cog", "engrenagem"),
                    ("lni-stats-up", "grafico"),
                    ("lni-users", "users"),
                    ("lni-layers", "design"),
                    ("lni-mobile", "mobile"),
                    ("lni-rocket", "rocket"),
                ],
                max_length=12,
            ),
        ),
    ]
