# Generated by Django 5.1.7 on 2025-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_servicemodel_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammodel",
            name="instagram",
            field=models.URLField(default="#", max_length=100),
        ),
    ]
