# Generated by Django 5.1.7 on 2025-03-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_teammodel_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargomodel",
            name="service",
            field=models.CharField(
                choices=[
                    ("Front-end Developer", "Front-end Developer"),
                    ("Back-end Developer", "Back-end Developer"),
                    ("ront-end Developer", "Front-end Developer"),
                    ("Designer de Produto", "Designer de Produto"),
                    ("Designer Lider", "Designer Lider"),
                ],
                max_length=50,
            ),
        ),
    ]
