# Generated by Django 5.1.7 on 2025-03-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_postmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChassiModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create", models.DateField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("numero", models.CharField(max_length=16, verbose_name="Número")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create", models.DateField(auto_now_add=True)),
                ("update", models.DateField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "car_brand",
                    models.CharField(max_length=50, verbose_name="Marca do Carro"),
                ),
                (
                    "car_model",
                    models.CharField(max_length=50, verbose_name="Modelo do carro"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=5, verbose_name="Preço"
                    ),
                ),
                (
                    "chassi",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.chassimodel",
                        verbose_name="Chassi do Carro",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
