# Generated by Django 5.1.7 on 2025-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_chassimodel_carmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Preço"
            ),
        ),
    ]
